Repository robot-lab/rcs-control-unit, pull requests merged in 2018-09, with the labels that each got.

#17 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement

#52 Reengineering move math class
  ComputerVisionSystem/CMakeLists.txt
  ComputerVisionSystem/CVS.cpp
  ComputerVisionSystem/CVS.h
  MathModule/CMakeLists.txt
  MathModule/FanucModel/FanucModel.cpp
  MathModule/FanucModel/FanucModel.h
  MathModule/FanucModel/RoboModelGeneral/RoboModelGeneral.cpp
  MathModule/FanucModel/RoboModelGeneral/RoboModelGeneral.h
  MathModule/MathModule.cpp
  MathModule/MathModule.h
  config.json
  config.txt
  main.cpp
Labels: enhancement, reengineering

#56 Fix shutting down and moc rca
  moc_servers/rca_server.py
  moc_servers/robot_server.py
  src/MathClass/MathClass.h
  src/RCAConnector/RCAConnector.cpp
Labels: bug

#60 Add cvs as lib and update parsers
  build.sh
  config.json
  moc_servers/robot_server.py
  src/CMakeLists.txt
  src/ComputerVisionSystem/CVS.cpp
  src/ComputerVisionSystem/CVS.h
  src/Executor/Executor.cpp
  src/Executor/Executor.h
  src/RCAConnector/RCAConnector.cpp
  src/RCAConnector/RCAConnector.h
  src/RobotConnector/RobotConnector.cpp
  src/RobotConnector/RobotConnector.h
  src/SensorAdapter/SensorAdapter.cpp
  src/main.cpp
Labels: enhancement
